
[build.environment]
  NPM_VERSION = "7.9.0"
  NODE_VERSION = "15.0.1"

[build]
  publish = "style-guide/_build/html"
  command = "cd style-guide && make clean html && cd .."

[context.production]
  publish = "style-guide/_build/html"
  command = "cd style-guide && make clean html && cd .."

[context.deploy-preview]
  publish = "style-guide/_build/html"
  command = "cd style-guide && make clean html && cd .."

[[redirects]]
  from = "/*"
  to = "/docs/style-guide/:splat"
  status = 301
  force = false